-------------------------------------------------------------------------------
Test set: DAOTests.ExameDAOTest
-------------------------------------------------------------------------------
Tests run: 8, Failures: 8, Errors: 0, Skipped: 0, Time elapsed: 32.497 sec <<< FAILURE!
DAOTests.ExameDAOTest.testDelete_exame()  Time elapsed: 4.045 sec  <<< FAILURE!
org.opentest4j.AssertionFailedError: Não há objeto com a id no banco de dados
	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:39)
	at org.junit.jupiter.api.Assertions.fail(Assertions.java:117)
	at DAOTests.ExameDAOTest.testDelete_exame(ExameDAOTest.java:132)

DAOTests.ExameDAOTest.testUpdate_exame()  Time elapsed: 4.076 sec  <<< FAILURE!
org.opentest4j.AssertionFailedError: Não há objeto com a id no banco de dados
	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:39)
	at org.junit.jupiter.api.Assertions.fail(Assertions.java:117)
	at DAOTests.ExameDAOTest.testUpdate_exame(ExameDAOTest.java:117)

DAOTests.ExameDAOTest.testGet_exames()  Time elapsed: 4.075 sec  <<< FAILURE!
java.lang.NullPointerException
	at model.ExameDAO.getExames(ExameDAO.java:51)
	at DAOTests.ExameDAOTest.testGet_exames(ExameDAOTest.java:59)

DAOTests.ExameDAOTest.testGet_exame()  Time elapsed: 4.064 sec  <<< FAILURE!
org.opentest4j.AssertionFailedError: Não há objeto com a id no banco de dados
	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:39)
	at org.junit.jupiter.api.Assertions.fail(Assertions.java:117)
	at DAOTests.ExameDAOTest.testGet_exame(ExameDAOTest.java:76)

DAOTests.ExameDAOTest.testCreate_exame()  Time elapsed: 4.076 sec  <<< FAILURE!
java.lang.NullPointerException
	at model.ExameDAO.getExames(ExameDAO.java:51)
	at DAOTests.ExameDAOTest.testCreate_exame(ExameDAOTest.java:42)

DAOTests.ExameDAOTest.testGet_examesDaConsulta()  Time elapsed: 4.049 sec  <<< FAILURE!
org.opentest4j.AssertionFailedError: Não há objeto com a id no banco de dados
	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:39)
	at org.junit.jupiter.api.Assertions.fail(Assertions.java:117)
	at DAOTests.ExameDAOTest.testGet_examesDaConsulta(ExameDAOTest.java:93)

DAOTests.ExameDAOTest.testGet_idDeleteExame()  Time elapsed: 4.041 sec  <<< FAILURE!
org.opentest4j.AssertionFailedError: Não há objeto com a id no banco de dados
	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:39)
	at org.junit.jupiter.api.Assertions.fail(Assertions.java:117)
	at DAOTests.ExameDAOTest.testGet_idDeleteExame(ExameDAOTest.java:163)

DAOTests.ExameDAOTest.testDelete_tipoExame()  Time elapsed: 4.07 sec  <<< FAILURE!
org.opentest4j.AssertionFailedError: Não há objeto com a id no banco de dados
	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:39)
	at org.junit.jupiter.api.Assertions.fail(Assertions.java:117)
	at DAOTests.ExameDAOTest.testDelete_tipoExame(ExameDAOTest.java:147)

